### PR TITLE
Update spog-controller.js

### PR DESCRIPTION
**Pull request by lisscasey**
IE11 supports 'indexOf' function and not 'includes'

### CODE REVIEW

**Review by amanulchowhury — APPROVED** [review]
Looks good. Merging now

**Comment by ghost** [comment]
This is in ES6, but should work if you are using Babel to transpile. I don't think IE11 supports ES6 classes

**Comment by amanulchowhury** [comment]
I agree with @vkumarw2. This is completely written ES6 and should be transpiled to use. And if you are using Babel as transpiler 'includes' should work fine.

**Comment by amanulchowhury** [comment]
Refer to https://github.com/babel/babel-preset-env/issues/203

**Comment by lisscasey** [comment]
yes, However we don't run our bower components through a transpiler. IndexOf will work without the need for babel

**Pull request merged**
